variable subnet_id {}
variable ecs_sg_id {}
variable alb_sg_id {}
variable tg_group_arn {}
variable ecs_task_execution_role {}
variable cloudwatch_log_group_id {}
variable ecr_repository_url {}
variable alb_listener {}
variable app_environment {}
variable app_name {}
