variable aws_region {}
variable vpc_cidr_block {}
variable public_subnet_cidrs {}
variable private_subnet_cidrs {}
variable app_name {}
variable app_env {}
variable bastion_ingress_ip {}
variable domain_name {}
variable dns_type {}
variable origin_id {}
variable s3_frontend_bucket {}
variable s3_aurora_bucket {}
variable bastion_host_key_name {}
variable bastion_host_instance_type {}
variable ecr_name {}
variable ecs_max_capacity {}
variable ecs_min_capacity {}
variable ecs_instance_type {}
variable ecs_desired_count {}
variable ecs_container_port {}
variable ecs_host_port {}
variable db_name {}
variable db_instance_class {}
variable engine {}
variable engine_ver {}
variable desired_read_replicas {}
variable master_username {}
variable master_password {}
variable replica_scale_max {}
variable replica_scale_min {}
variable db_subnet_group_name {}
variable ecs_ingress_cidr_blocks {}
variable rds_cidr_blocks {}
variable rds_cluster_identifier {}